// ============================================================
// AheadSub — Collocation & Multi-Word Phrase Engine
// Detects idioms, compound nouns, prepositional phrases, and
// collocations in subtitles for interactive language learning.
// Provides local instant translations into Uzbek.
// ============================================================

export interface DetectedPhrase {
  phraseText: string;
  rawText: string;
  startIndex: number;
  endIndex: number;
  wordIndices: number[];
  translationUz?: string;
  translationEn?: string;
  category: 'idiom' | 'collocation' | 'compound' | 'name';
}

// Built-in high-frequency collocations, idioms, and compound phrases
export const RUSSIAN_COLLOCATIONS: Record<
  string,
  { uz: string; en: string; category: 'idiom' | 'collocation' | 'compound' | 'name' }
> = {
  // Roles, Titles & Media Collocations
  'ректор академии': { uz: 'Akademiya rektori', en: 'Rector of the academy', category: 'collocation' },
  'магическая академия': { uz: 'Sehrgarlik akademiyasi', en: 'Magic academy', category: 'collocation' },
  'магической академии': { uz: 'Sehrgarlik akademiyasi', en: 'Magic academy', category: 'collocation' },
  'король демонов': { uz: 'Demonlar qiroli', en: 'Demon king', category: 'collocation' },
  'короля демонов': { uz: 'Demonlar qiroli', en: 'Demon king', category: 'collocation' },
  'мастер меча': { uz: 'Qilich ustasi', en: 'Sword master', category: 'collocation' },
  'директор школы': { uz: 'Maktab direktori', en: 'School principal', category: 'collocation' },
  'глава совета': { uz: "Kengash boshlig'i", en: 'Head of council', category: 'collocation' },
  'главный герой': { uz: 'Bosh qahramon', en: 'Main character', category: 'collocation' },
  'главного героя': { uz: 'Bosh qahramon', en: 'Main character', category: 'collocation' },
  'темный маг': { uz: "Qorong'u sehrgar", en: 'Dark wizard', category: 'collocation' },
  'темного мага': { uz: "Qorong'u sehrgar", en: 'Dark wizard', category: 'collocation' },
  'рыцарь ордена': { uz: 'Orden ritsari', en: 'Knight of the order', category: 'collocation' },
  'высший ранг': { uz: 'Yuqori daraja / martaba', en: 'Highest rank', category: 'collocation' },
  'тайное общество': { uz: 'Maxfiy jamiyat', en: 'Secret society', category: 'collocation' },
  'точка зрения': { uz: 'Nuqtai nazar', en: 'Point of view', category: 'collocation' },
  'точки зрения': { uz: 'Nuqtai nazar', en: 'Point of view', category: 'collocation' },
  'образ жизни': { uz: 'Hayot tarzi', en: 'Lifestyle', category: 'collocation' },

  // Conversational Idioms & Phrasal Expressions
  'вроде как': { uz: "kabi / go'yoki", en: 'kind of / as if', category: 'idiom' },
  'как будто': { uz: "go'yo / xuddi", en: 'as if / like', category: 'idiom' },
  'до сих пор': { uz: 'shu paytgacha / hanuzgacha', en: 'until now / so far', category: 'idiom' },
  'с тех пор': { uz: "o'shandan beri", en: 'since then', category: 'idiom' },
  'на самом деле': { uz: 'aslida / haqiqatda', en: 'actually / in fact', category: 'idiom' },
  'в конце концов': { uz: 'oxir-oqibat / so‘ngida', en: 'in the end / after all', category: 'idiom' },
  'друг друга': { uz: 'bir-birini', en: 'each other', category: 'idiom' },
  'друг с другом': { uz: 'bir-biri bilan', en: 'with each other', category: 'idiom' },
  'друг другу': { uz: 'bir-biriga', en: 'to each other', category: 'idiom' },
  'друг о друге': { uz: 'bir-biri haqida', en: 'about each other', category: 'idiom' },
  'дело в том': { uz: 'gap shundaki', en: 'the thing is', category: 'idiom' },
  'в то же время': { uz: 'shu bilan birga', en: 'at the same time', category: 'idiom' },
  'по крайней мере': { uz: "kamida / hech bo'lmaganda", en: 'at least', category: 'idiom' },
  'обратить внимание': { uz: "e'tibor qaratmoq", en: 'pay attention', category: 'idiom' },
  'обрати внимание': { uz: "e'tibor ber", en: 'pay attention', category: 'idiom' },
  'иметь в виду': { uz: 'nazarda tutmoq', en: 'have in mind / mean', category: 'idiom' },
  'имею в виду': { uz: 'nazarda tutyapman', en: 'I mean', category: 'idiom' },
  'имей в виду': { uz: 'yodda tut / bilginki', en: 'keep in mind', category: 'idiom' },
  'с ума сойти': { uz: 'aqldan ozish / daxshat', en: 'go crazy / insane', category: 'idiom' },
  'сошел с ума': { uz: 'aqldan ozdi', en: 'went crazy', category: 'idiom' },
  'сошла с ума': { uz: 'aqldan ozdi', en: 'went crazy', category: 'idiom' },
  'только что': { uz: 'hozirgina / yangi', en: 'just now', category: 'idiom' },
  'перед тем как': { uz: 'avval / oldin', en: 'before', category: 'idiom' },
  'после того как': { uz: "keyin / so'ng", en: 'after', category: 'idiom' },
  'потому что': { uz: 'chunki', en: 'because', category: 'idiom' },
  'так как': { uz: 'chunki / sababli', en: 'since / because', category: 'idiom' },
  'ничего себе': { uz: "voy-bo' / ana xolos", en: 'wow / no way', category: 'idiom' },
  'само собой': { uz: "o'z-o'zidan ma'lum", en: 'of course / naturally', category: 'idiom' },
  'без сомнения': { uz: 'shubhasiz', en: 'without a doubt', category: 'idiom' },
  'тем не менее': { uz: 'shunga qaramay', en: 'nevertheless', category: 'idiom' },
  'вряд ли': { uz: 'dargumon / ehtimoldan yiroq', en: 'hardly / unlikely', category: 'idiom' },
  'несмотря на': { uz: 'qaramasdan', en: 'despite', category: 'idiom' },
  'в течение': { uz: 'davomida', en: 'during / throughout', category: 'idiom' },
  'в связи с': { uz: 'munosabati bilan', en: 'in connection with', category: 'idiom' },
  'как раз': { uz: 'aynan / ayni vaqtda', en: 'just / exactly', category: 'idiom' },
  'изо всех сил': { uz: 'bor kuchi bilan', en: "with all one's might", category: 'idiom' },
  'во что бы то ни стало': { uz: 'har qanday holatda', en: 'at all costs', category: 'idiom' },
  'не то чтобы': { uz: "unchalik emas-ku / go'yoki", en: 'not that', category: 'idiom' },
  'так сказать': { uz: "ta'bir joiz bo'lsa", en: 'so to speak', category: 'idiom' },
  'кстати говоря': { uz: 'aytganday / darvoqe', en: 'by the way', category: 'idiom' },
  'в любом случае': { uz: 'har qanday holatda', en: 'in any case', category: 'idiom' },
  'в таком случае': { uz: 'unday bo‘lsa / bu holda', en: 'in that case', category: 'idiom' },
  'скорее всего': { uz: 'katta ehtimol bilan', en: 'most likely', category: 'idiom' },
  'может быть': { uz: "balki / bo'lishi mumkin", en: 'maybe / perhaps', category: 'idiom' },
  'должно быть': { uz: 'aftidan / bo‘lsa kerak', en: 'must be', category: 'idiom' },
  'не имеет значения': { uz: "ahamiyati yo'q", en: "doesn't matter", category: 'idiom' },
  'все равно': { uz: 'baribir', en: 'all the same', category: 'idiom' },
  'вместе с': { uz: 'bilan birga', en: 'together with', category: 'idiom' },
  'до тех пор': { uz: "o'sha paytgacha", en: 'until then', category: 'idiom' },
  'ни за что': { uz: 'aslo / sira ham', en: 'no way / never', category: 'idiom' },
  'ни в коем случае': { uz: 'hech qanday holatda', en: 'under no circumstances', category: 'idiom' },
  'судя по всему': { uz: 'ko‘rinishidan / aftidan', en: 'judging by appearances', category: 'idiom' },
  'на первый взгляд': { uz: 'birinchi qarashda', en: 'at first glance', category: 'idiom' },
  'со временем': { uz: "vaqt o'tishi bilan", en: 'over time', category: 'idiom' },
  'рука об руку': { uz: "yonma-yon / qo'lma-qo'l", en: 'hand in hand', category: 'idiom' },
  'с глазу на глаз': { uz: 'yakkama-yakka', en: 'face to face', category: 'idiom' },
  'дать знать': { uz: 'xabar bermoq', en: 'let know', category: 'idiom' },
  'принимать решение': { uz: 'qaror qabul qilmoq', en: 'make a decision', category: 'idiom' },
  'принять решение': { uz: 'qaror qabul qilmoq', en: 'make a decision', category: 'idiom' },
  'сделать вывод': { uz: 'xulosa chiqarmoq', en: 'make a conclusion', category: 'idiom' },
};

// High-frequency single word Russian -> Uzbek instant dictionary (0.0ms lookup)
export const INSTANT_UZBEK_WORDS: Record<string, { uz: string; pos?: string; base?: string }> = {
  // --- Personal & Demonstrative Pronouns ---
  я: { uz: 'men', pos: 'PRON', base: 'я' },
  меня: { uz: 'meni / o‘zimni', pos: 'PRON', base: 'я' },
  мне: { uz: 'menga', pos: 'PRON', base: 'я' },
  мной: { uz: 'men bilan', pos: 'PRON', base: 'я' },
  мною: { uz: 'men bilan', pos: 'PRON', base: 'я' },
  ты: { uz: 'sen', pos: 'PRON', base: 'ты' },
  тебя: { uz: 'seni', pos: 'PRON', base: 'ты' },
  тебе: { uz: 'senga', pos: 'PRON', base: 'ты' },
  тобой: { uz: 'sen bilan', pos: 'PRON', base: 'ты' },
  тобою: { uz: 'sen bilan', pos: 'PRON', base: 'ты' },
  он: { uz: 'u (erkak)', pos: 'PRON', base: 'он' },
  его: { uz: 'uning / uni', pos: 'PRON', base: 'он' },
  него: { uz: 'uning / undan', pos: 'PRON', base: 'он' },
  ему: { uz: 'unga', pos: 'PRON', base: 'он' },
  нему: { uz: 'unga / tomoniga', pos: 'PRON', base: 'он' },
  им: { uz: 'u bilan / ularga', pos: 'PRON', base: 'он' },
  ним: { uz: 'u bilan', pos: 'PRON', base: 'он' },
  нем: { uz: 'unda / u haqida', pos: 'PRON', base: 'он' },
  она: { uz: 'u (ayol)', pos: 'PRON', base: 'она' },
  ее: { uz: 'uning / uni', pos: 'PRON', base: 'она' },
  её: { uz: 'uning / uni', pos: 'PRON', base: 'она' },
  нее: { uz: 'uning / undan', pos: 'PRON', base: 'она' },
  неё: { uz: 'uning / undan', pos: 'PRON', base: 'она' },
  ей: { uz: 'unga', pos: 'PRON', base: 'она' },
  ней: { uz: 'unda / unga / u bilan', pos: 'PRON', base: 'она' },
  ею: { uz: 'u bilan', pos: 'PRON', base: 'она' },
  оно: { uz: 'u (o‘rta jins)', pos: 'PRON', base: 'оно' },
  мы: { uz: 'biz', pos: 'PRON', base: 'мы' },
  нас: { uz: 'bizni / bizda', pos: 'PRON', base: 'мы' },
  нам: { uz: 'bizga', pos: 'PRON', base: 'мы' },
  нами: { uz: 'biz bilan', pos: 'PRON', base: 'мы' },
  наш: { uz: 'bizning', pos: 'PRON', base: 'наш' },
  наша: { uz: 'bizning', pos: 'PRON', base: 'наш' },
  наше: { uz: 'bizning', pos: 'PRON', base: 'наш' },
  наши: { uz: 'bizning', pos: 'PRON', base: 'наш' },
  вы: { uz: 'siz / sizlar', pos: 'PRON', base: 'вы' },
  вас: { uz: 'sizni / sizlarda', pos: 'PRON', base: 'вы' },
  вам: { uz: 'sizga', pos: 'PRON', base: 'вы' },
  вами: { uz: 'siz bilan', pos: 'PRON', base: 'вы' },
  ваш: { uz: 'sizning', pos: 'PRON', base: 'ваш' },
  ваша: { uz: 'sizning', pos: 'PRON', base: 'ваш' },
  ваше: { uz: 'sizning', pos: 'PRON', base: 'ваш' },
  ваши: { uz: 'sizning', pos: 'PRON', base: 'ваш' },
  они: { uz: 'ular', pos: 'PRON', base: 'они' },
  их: { uz: 'ularning / ularni', pos: 'PRON', base: 'они' },
  них: { uz: 'ularning / ulardan / ularda', pos: 'PRON', base: 'они' },
  ними: { uz: 'ular bilan', pos: 'PRON', base: 'они' },
  это: { uz: 'bu / bu narsa', pos: 'PRON', base: 'этот' },
  этот: { uz: 'bu / ushbu', pos: 'PRON', base: 'этот' },
  эта: { uz: 'bu / ushbu', pos: 'PRON', base: 'этоt' },
  эти: { uz: 'bular / ushbu', pos: 'PRON', base: 'этот' },
  этого: { uz: 'buning / buni', pos: 'PRON', base: 'этот' },
  этом: { uz: 'bunda / bu haqida', pos: 'PRON', base: 'этот' },
  этому: { uz: 'bunga', pos: 'PRON', base: 'этот' },
  этой: { uz: 'buning / bunga / bu bilan', pos: 'PRON', base: 'этот' },
  этим: { uz: 'bu bilan / bularga', pos: 'PRON', base: 'этот' },
  этих: { uz: 'bularning / bularni', pos: 'PRON', base: 'этот' },
  то: { uz: 'o‘sha / u narsa', pos: 'PRON', base: 'тот' },
  тот: { uz: 'o‘sha / ana u', pos: 'PRON', base: 'тот' },
  та: { uz: 'o‘sha', pos: 'PRON', base: 'тот' },
  те: { uz: 'o‘shalar', pos: 'PRON', base: 'тот' },
  того: { uz: 'o‘shaning / o‘shani', pos: 'PRON', base: 'тот' },
  том: { uz: 'o‘shanda / u haqida', pos: 'PRON', base: 'тот' },
  тому: { uz: 'o‘shanga', pos: 'PRON', base: 'тот' },
  той: { uz: 'o‘shaning / o‘shanga', pos: 'PRON', base: 'тот' },
  тем: { uz: 'o‘sha bilan / o‘shalarga', pos: 'PRON', base: 'тот' },
  тех: { uz: 'o‘shalarning / o‘shalarni', pos: 'PRON', base: 'тот' },
  все: { uz: 'hamma / barcha', pos: 'PRON', base: 'весь' },
  всё: { uz: 'hamma narsa / bari', pos: 'PRON', base: 'весь' },
  весь: { uz: 'butun / barcha', pos: 'PRON', base: 'весь' },
  вся: { uz: 'butun / barcha', pos: 'PRON', base: 'весь' },
  всего: { uz: 'hammasi / jami', pos: 'PRON', base: 'весь' },
  всему: { uz: 'hammasiga', pos: 'PRON', base: 'весь' },
  всех: { uz: 'hammaning / barchani', pos: 'PRON', base: 'весь' },
  всем: { uz: 'hammaga / barchaga', pos: 'PRON', base: 'весь' },
  себя: { uz: 'o‘zini', pos: 'PRON', base: 'себя' },
  себе: { uz: 'o‘ziga', pos: 'PRON', base: 'себя' },
  собой: { uz: 'o‘zi bilan', pos: 'PRON', base: 'себя' },
  собою: { uz: 'o‘zi bilan', pos: 'PRON', base: 'себя' },
  сам: { uz: 'o‘zi (erkak)', pos: 'PRON', base: 'сам' },
  sama: { uz: 'o‘zi (ayol)', pos: 'PRON', base: 'сам' },
  сама: { uz: 'o‘zi (ayol)', pos: 'PRON', base: 'сам' },
  само: { uz: 'o‘zi', pos: 'PRON', base: 'сам' },
  сами: { uz: 'o‘zlari', pos: 'PRON', base: 'сам' },
  мой: { uz: 'mening', pos: 'PRON', base: 'мой' },
  моя: { uz: 'mening', pos: 'PRON', base: 'мой' },
  мое: { uz: 'mening', pos: 'PRON', base: 'мой' },
  моё: { uz: 'mening', pos: 'PRON', base: 'мой' },
  мои: { uz: 'mening', pos: 'PRON', base: 'мой' },
  моего: { uz: 'mening', pos: 'PRON', base: 'мой' },
  моей: { uz: 'mening', pos: 'PRON', base: 'мой' },
  моих: { uz: 'mening', pos: 'PRON', base: 'мой' },
  твой: { uz: 'sening', pos: 'PRON', base: 'твой' },
  твоя: { uz: 'sening', pos: 'PRON', base: 'твой' },
  твое: { uz: 'sening', pos: 'PRON', base: 'твой' },
  твоё: { uz: 'sening', pos: 'PRON', base: 'твой' },
  твои: { uz: 'sening', pos: 'PRON', base: 'твой' },
  свой: { uz: 'o‘zining', pos: 'PRON', base: 'свой' },
  своя: { uz: 'o‘zining', pos: 'PRON', base: 'свой' },
  свое: { uz: 'o‘zining', pos: 'PRON', base: 'свой' },
  своё: { uz: 'o‘zining', pos: 'PRON', base: 'свой' },
  свои: { uz: 'o‘zining', pos: 'PRON', base: 'свой' },
  своих: { uz: 'o‘zining', pos: 'PRON', base: 'свой' },
  чей: { uz: 'kimning', pos: 'PRON', base: 'чей' },
  кто: { uz: 'kim', pos: 'PRON', base: 'кто' },
  что: { uz: 'nima / -ki', pos: 'PRON', base: 'что' },
  какой: { uz: 'qanday / qanaqa', pos: 'PRON', base: 'какой' },
  какая: { uz: 'qanday / qanaqa', pos: 'PRON', base: 'какой' },
  какое: { uz: 'qanday / qanaqa', pos: 'PRON', base: 'какой' },
  какие: { uz: 'qanday / qanaqa', pos: 'PRON', base: 'какой' },

  // --- Prepositions & Conjunctions & Particles ---
  в: { uz: 'ichida / da / ga', pos: 'PREP', base: 'в' },
  во: { uz: 'ichida / da', pos: 'PREP', base: 'в' },
  на: { uz: 'ustida / da / ga', pos: 'PREP', base: 'на' },
  с: { uz: 'bilan / dan', pos: 'PREP', base: 'с' },
  со: { uz: 'bilan / dan', pos: 'PREP', base: 'с' },
  по: { uz: 'bo‘yicha / bo‘ylab', pos: 'PREP', base: 'по' },
  к: { uz: 'tomon / ga', pos: 'PREP', base: 'к' },
  ко: { uz: 'tomon / ga', pos: 'PREP', base: 'к' },
  из: { uz: 'dan / ichidan', pos: 'PREP', base: 'из' },
  изо: { uz: 'dan', pos: 'PREP', base: 'из' },
  у: { uz: 'huzurida / -da bor', pos: 'PREP', base: 'у' },
  о: { uz: 'haqida', pos: 'PREP', base: 'о' },
  об: { uz: 'haqida', pos: 'PREP', base: 'о' },
  обо: { uz: 'haqida', pos: 'PREP', base: 'о' },
  за: { uz: 'orqasida / uchun / ketidan', pos: 'PREP', base: 'за' },
  от: { uz: 'dan / tomonidan', pos: 'PREP', base: 'от' },
  ото: { uz: 'dan', pos: 'PREP', base: 'от' },
  до: { uz: 'gacha / oldin', pos: 'PREP', base: 'до' },
  для: { uz: 'uchun', pos: 'PREP', base: 'для' },
  без: { uz: 'siz / be-', pos: 'PREP', base: 'без' },
  под: { uz: 'ostida / tagida', pos: 'PREP', base: 'под' },
  над: { uz: 'tepasida / ustida', pos: 'PREP', base: 'над' },
  перед: { uz: 'oldida', pos: 'PREP', base: 'перед' },
  при: { uz: 'huzurida / paytida', pos: 'PREP', base: 'при' },
  через: { uz: 'orqali / o‘tib', pos: 'PREP', base: 'через' },
  между: { uz: 'orasida / o‘rtasida', pos: 'PREP', base: 'между' },
  и: { uz: 'va / ham', pos: 'CONJ', base: 'и' },
  но: { uz: 'lekin / ammo / biroq', pos: 'CONJ', base: 'но' },
  а: { uz: 'esa / ammo', pos: 'CONJ', base: 'а' },
  или: { uz: 'yoki', pos: 'CONJ', base: 'или' },
  чтобы: { uz: 'uchun / maqsadida', pos: 'CONJ', base: 'чтобы' },
  если: { uz: 'agar', pos: 'CONJ', base: 'если' },
  как: { uz: 'qanday / kabi', pos: 'CONJ', base: 'как' },
  так: { uz: 'shunday / demak', pos: 'ADV', base: 'так' },
  тоже: { uz: 'ham / shuningdek', pos: 'ADV', base: 'тоже' },
  также: { uz: 'shuningdek / ham', pos: 'ADV', base: 'также' },
  же: { uz: 'esa / axir / -ku', pos: 'PART', base: 'же' },
  ли: { uz: '-mi (so‘roq qo‘shimchasi)', pos: 'PART', base: 'ли' },
  бы: { uz: '-ardi (shart / istak mayli)', pos: 'PART', base: 'бы' },
  не: { uz: 'emas / -ma (inkor)', pos: 'PART', base: 'не' },
  ни: { uz: 'hech / na ... na', pos: 'PART', base: 'ни' },
  уже: { uz: 'allaqachon', pos: 'ADV', base: 'уже' },
  еще: { uz: 'yana / hali', pos: 'ADV', base: 'еще' },
  ещё: { uz: 'yana / hali', pos: 'ADV', base: 'еще' },
  только: { uz: 'faqat / hozirgina', pos: 'ADV', base: 'только' },
  даже: { uz: 'hatto', pos: 'PART', base: 'даже' },
  ведь: { uz: 'axir / axir shu', pos: 'PART', base: 'ведь' },
  вот: { uz: 'mana', pos: 'PART', base: 'вот' },
  вон: { uz: 'ana / ana u yerda', pos: 'PART', base: 'вон' },
  да: { uz: 'ha / va', pos: 'PART', base: 'да' },
  нет: { uz: 'yo‘q', pos: 'PART', base: 'нет' },

  // --- Common Verbs & Copulas ---
  быть: { uz: 'bo‘lmoq', pos: 'VERB', base: 'быть' },
  есть: { uz: 'bor / mavjud / hisoblanadi', pos: 'VERB', base: 'быть' },
  был: { uz: 'edi / bo‘lgan', pos: 'VERB', base: 'быть' },
  была: { uz: 'edi (ayol)', pos: 'VERB', base: 'быть' },
  было: { uz: 'edi / bo‘ldi', pos: 'VERB', base: 'быть' },
  были: { uz: 'edilar / bo‘lishdi', pos: 'VERB', base: 'быть' },
  будет: { uz: 'bo‘ladi', pos: 'VERB', base: 'быть' },
  будут: { uz: 'bo‘ladilar / bo‘lishadi', pos: 'VERB', base: 'быть' },
  буду: { uz: 'bo‘laman', pos: 'VERB', base: 'быть' },
  будешь: { uz: 'bo‘lasan', pos: 'VERB', base: 'быть' },
  сказать: { uz: 'aytmoq / demoq', pos: 'VERB', base: 'сказать' },
  сказал: { uz: 'aytdi / dedi', pos: 'VERB', base: 'сказать' },
  сказала: { uz: 'aytdi (ayol)', pos: 'VERB', base: 'сказать' },
  скажи: { uz: 'ayt / gapir', pos: 'VERB', base: 'сказать' },
  говорить: { uz: 'gapirmoq', pos: 'VERB', base: 'говорить' },
  говорит: { uz: 'gapiryapti / aytadi', pos: 'VERB', base: 'говорить' },
  знать: { uz: 'bilmoq', pos: 'VERB', base: 'знать' },
  знаю: { uz: 'bilaman', pos: 'VERB', base: 'знать' },
  знаешь: { uz: 'bilasan', pos: 'VERB', base: 'знать' },
  знает: { uz: 'biladi', pos: 'VERB', base: 'знать' },
  знал: { uz: 'bilar edi', pos: 'VERB', base: 'знать' },
  понять: { uz: 'tushunmoq / anglamoq', pos: 'VERB', base: 'понять' },
  понял: { uz: 'tushundi / tushundim', pos: 'VERB', base: 'понять' },
  поняла: { uz: 'tushundim / tushundi (ayol)', pos: 'VERB', base: 'понять' },
  поняли: { uz: 'tushunishdi / tushundik', pos: 'VERB', base: 'понять' },
  понимаю: { uz: 'tushunyapman / bilaman', pos: 'VERB', base: 'понимать' },
  понимаешь: { uz: 'tushunyapsanmi', pos: 'VERB', base: 'понимать' },
  мочь: { uz: 'qila olmoq', pos: 'VERB', base: 'мочь' },
  могу: { uz: 'qila olaman', pos: 'VERB', base: 'мочь' },
  может: { uz: 'qila oladi / mumkin', pos: 'VERB', base: 'мочь' },
  могут: { uz: 'qila oladilar', pos: 'VERB', base: 'мочь' },
  мог: { uz: 'qila olar edi', pos: 'VERB', base: 'мочь' },
  могла: { uz: 'qila olar edi (ayol)', pos: 'VERB', base: 'мочь' },
  хотеть: { uz: 'xohlamoq / istamoq', pos: 'VERB', base: 'хотеть' },
  хочу: { uz: 'xohlayman', pos: 'VERB', base: 'хотеть' },
  хочет: { uz: 'xohlaydi', pos: 'VERB', base: 'хотеть' },
  хотят: { uz: 'xohlashadi', pos: 'VERB', base: 'хотеть' },
  хотел: { uz: 'xohlagan edi', pos: 'VERB', base: 'хотеть' },
  видеть: { uz: 'ko‘rmoq', pos: 'VERB', base: 'видеть' },
  вижу: { uz: 'ko‘ryapman', pos: 'VERB', base: 'видеть' },
  видит: { uz: 'ko‘radi / ko‘ryapti', pos: 'VERB', base: 'видеть' },
  видел: { uz: 'ko‘rgan edi', pos: 'VERB', base: 'видеть' },
  увидел: { uz: 'ko‘rib qoldi', pos: 'VERB', base: 'увидеть' },
  думать: { uz: 'o‘ylamoq', pos: 'VERB', base: 'думать' },
  думаю: { uz: 'o‘ylayman', pos: 'VERB', base: 'думать' },
  думает: { uz: 'o‘ylaydi', pos: 'VERB', base: 'думать' },
  думал: { uz: 'o‘ylagan edi', pos: 'VERB', base: 'думать' },
  делать: { uz: 'qilmoq / bajarmoq', pos: 'VERB', base: 'делать' },
  делаю: { uz: 'qilyapman', pos: 'VERB', base: 'делать' },
  делает: { uz: 'qilyapti', pos: 'VERB', base: 'делать' },
  сделать: { uz: 'qilib qo‘ymoq', pos: 'VERB', base: 'сделать' },
  сделал: { uz: 'qildi / bajardi', pos: 'VERB', base: 'сделать' },
  идти: { uz: 'bormoq / ketmoq', pos: 'VERB', base: 'идти' },
  идет: { uz: 'ketyapti / boryapti', pos: 'VERB', base: 'идти' },
  идёт: { uz: 'ketyapti / boryapti', pos: 'VERB', base: 'идти' },
  шел: { uz: 'ketayotgan edi', pos: 'VERB', base: 'идти' },
  пошел: { uz: 'ketdi / jo‘nadi', pos: 'VERB', base: 'пойти' },
  пошли: { uz: 'ketdik / qani yuring', pos: 'VERB', base: 'пойти' },
  дать: { uz: 'bermoq', pos: 'VERB', base: 'дать' },
  дал: { uz: 'berdi', pos: 'VERB', base: 'дать' },
  дала: { uz: 'berdi (ayol)', pos: 'VERB', base: 'дать' },
  давай: { uz: 'qani / kel / mayli', pos: 'VERB', base: 'давать' },
  дайте: { uz: 'bering', pos: 'VERB', base: 'дать' },
  смотреть: { uz: 'qaramoq', pos: 'VERB', base: 'смотреть' },
  смотри: { uz: 'qara / boq', pos: 'VERB', base: 'смотреть' },
  смотрит: { uz: 'qarayapti', pos: 'VERB', base: 'смотреть' },
  ждать: { uz: 'kutmoq', pos: 'VERB', base: 'ждать' },
  жди: { uz: 'kut / sabr qil', pos: 'VERB', base: 'ждать' },
  ждет: { uz: 'kutyapti', pos: 'VERB', base: 'ждать' },
  слушать: { uz: 'eshitmoq / tinglamoq', pos: 'VERB', base: 'слушать' },
  слушай: { uz: 'eshit / quloq sol', pos: 'VERB', base: 'слушать' },
  жить: { uz: 'yashamoq', pos: 'VERB', base: 'жить' },
  любить: { uz: 'sevmoq / yaxshi ko‘rmoq', pos: 'VERB', base: 'любить' },
  люблю: { uz: 'sevaman / yaxshi ko‘raman', pos: 'VERB', base: 'любить' },
  любит: { uz: 'sevadi / yaxshi ko‘radi', pos: 'VERB', base: 'любить' },
  стать: { uz: 'bo‘lmoq / aylanish', pos: 'VERB', base: 'стать' },
  стал: { uz: 'bo‘ldi / boshladi', pos: 'VERB', base: 'стать' },
  стала: { uz: 'bo‘ldi (ayol)', pos: 'VERB', base: 'стать' },
  станет: { uz: 'bo‘ladi / aylanadi', pos: 'VERB', base: 'стать' },
  надо: { uz: 'kerak / lozim', pos: 'ADV', base: 'надо' },
  нужно: { uz: 'kerak / zarur', pos: 'ADV', base: 'нужно' },
  нужен: { uz: 'kerak', pos: 'ADJ', base: 'нужный' },
  нужна: { uz: 'kerak (ayol)', pos: 'ADJ', base: 'нужный' },
  можно: { uz: 'mumkin / ruxsat', pos: 'ADV', base: 'можно' },
  нельзя: { uz: 'mumkin emas / taqiqlangan', pos: 'ADV', base: 'нельзя' },

  // --- Anime / Film Context Vocab ---
  прелесть: { uz: 'joziba / go‘zallik / ajoyiblik', pos: 'NOUN', base: 'прелесть' },
  ректор: { uz: 'rektor (rahbar)', pos: 'NOUN', base: 'ректор' },
  академии: { uz: 'akademiya', pos: 'NOUN', base: 'академия' },
  академия: { uz: 'akademiya', pos: 'NOUN', base: 'академия' },
  магия: { uz: 'sehr / sehrgarlik', pos: 'NOUN', base: 'магия' },
  магии: { uz: 'sehr', pos: 'NOUN', base: 'магия' },
  сила: { uz: 'kuch / qudrat', pos: 'NOUN', base: 'сила' },
  силы: { uz: 'kuchlar', pos: 'NOUN', base: 'сила' },
  человек: { uz: 'inson / odam', pos: 'NOUN', base: 'человек' },
  люди: { uz: 'odamlar', pos: 'NOUN', base: 'человек' },
  друг: { uz: 'do‘st', pos: 'NOUN', base: 'друг' },
  друзья: { uz: 'do‘stlar', pos: 'NOUN', base: 'друг' },
  время: { uz: 'vaqt', pos: 'NOUN', base: 'время' },
  дело: { uz: 'ish / masala', pos: 'NOUN', base: 'дело' },
  жизнь: { uz: 'hayot', pos: 'NOUN', base: 'жизнь' },
  день: { uz: 'kun', pos: 'NOUN', base: 'день' },
  рука: { uz: 'qo‘l', pos: 'NOUN', base: 'рука' },
  руки: { uz: 'qo‘llar', pos: 'NOUN', base: 'рука' },
  глаз: { uz: 'ko‘z', pos: 'NOUN', base: 'глаз' },
  глаза: { uz: 'ko‘zlar', pos: 'NOUN', base: 'глаз' },
  слово: { uz: 'so‘z', pos: 'NOUN', base: 'слово' },
  слова: { uz: 'so‘zlar', pos: 'NOUN', base: 'слово' },
  место: { uz: 'joy / o‘rin', pos: 'NOUN', base: 'место' },
  голова: { uz: 'bosh', pos: 'NOUN', base: 'голова' },
  дом: { uz: 'uy', pos: 'NOUN', base: 'дом' },
  мир: { uz: 'dunyo / olam', pos: 'NOUN', base: 'мир' },
  конец: { uz: 'oxir / yakun', pos: 'NOUN', base: 'конец' },
  город: { uz: 'shahar', pos: 'NOUN', base: 'город' },
  голос: { uz: 'ovoz', pos: 'NOUN', base: 'голос' },
  мальчик: { uz: 'o‘g‘il bola', pos: 'NOUN', base: 'мальчик' },
  девушка: { uz: 'qiz bola', pos: 'NOUN', base: 'девушка' },
  король: { uz: 'qirol / podshoh', pos: 'NOUN', base: 'король' },
  учитель: { uz: 'o‘qituvchi / ustoz', pos: 'NOUN', base: 'учитель' },
  ученик: { uz: 'o‘quvchi / shogird', pos: 'NOUN', base: 'ученик' },
  школа: { uz: 'maktab', pos: 'NOUN', base: 'школа' },
  враг: { uz: 'dushman', pos: 'NOUN', base: 'враг' },
  битва: { uz: 'jang / to‘qnashuv', pos: 'NOUN', base: 'битва' },
  меч: { uz: 'qilich', pos: 'NOUN', base: 'меч' },
  щит: { uz: 'qalqon', pos: 'NOUN', base: 'щит' },
  огонь: { uz: 'olov', pos: 'NOUN', base: 'огонь' },
  вода: { uz: 'suv', pos: 'NOUN', base: 'вода' },
  ветер: { uz: 'shamol', pos: 'NOUN', base: 'ветер' },
  свет: { uz: 'nur / yorug‘lik', pos: 'NOUN', base: 'свет' },
  тьма: { uz: 'zulmat / qorong‘ulik', pos: 'NOUN', base: 'тьма' },
  правда: { uz: 'haqiqat / to‘g‘ri', pos: 'NOUN', base: 'правда' },
  хорошо: { uz: 'yaxshi', pos: 'ADV', base: 'хороший' },
  плохо: { uz: 'yomon', pos: 'ADV', base: 'плохой' },
  быстро: { uz: 'tezda', pos: 'ADV', base: 'быстрый' },
  медленно: { uz: 'sekin', pos: 'ADV', base: 'медленный' },
  сейчас: { uz: 'hozir', pos: 'ADV', base: 'сейчас' },
  потом: { uz: 'keyin', pos: 'ADV', base: 'потом' },
  всегда: { uz: 'doimo / har doim', pos: 'ADV', base: 'всегда' },
  никогда: { uz: 'hech qachon', pos: 'ADV', base: 'никогда' },
  здесь: { uz: 'bu yerda', pos: 'ADV', base: 'здесь' },
  там: { uz: 'u yerda', pos: 'ADV', base: 'там' },
  куда: { uz: 'qayerga', pos: 'ADV', base: 'куда' },
  где: { uz: 'qayerda', pos: 'ADV', base: 'где' },
  почему: { uz: 'nega / nima uchun', pos: 'ADV', base: 'почему' },
  зачем: { uz: 'nima maqsadda / nega', pos: 'ADV', base: 'зачем' },
  когда: { uz: 'qachon', pos: 'ADV', base: 'когда' },
  сколько: { uz: 'qancha', pos: 'NUM', base: 'сколько' },
  очень: { uz: 'juda', pos: 'ADV', base: 'очень' },
  много: { uz: 'ko‘p', pos: 'ADV', base: 'много' },
  мало: { uz: 'kam', pos: 'ADV', base: 'мало' },
  спасибо: { uz: 'rahmat', pos: 'INTJ', base: 'спасибо' },
  пожалуйста: { uz: 'marhamat / iltimos', pos: 'INTJ', base: 'пожалуйста' },
  привет: { uz: 'salom', pos: 'INTJ', base: 'привет' },
};

/**
 * Clean a token to plain lowercase letters/numbers
 */
export function cleanToken(text: string): string {
  return text.trim()
    .replace(/[’`]/g, "'")
    .replace(/^[^\p{L}\p{N}']+|[^\p{L}\p{N}']+$/gu, '')
    .toLowerCase();
}

/**
 * Scan a list of word tokens and detect multi-word collocations, idioms, and phrases.
 * Returns an array of detected phrases with their token index spans.
 */
export function detectCollocations(words: string[]): DetectedPhrase[] {
  const detected: DetectedPhrase[] = [];
  const n = words.length;
  const usedIndices = new Set<number>();

  const cleaned = words.map(cleanToken);

  // 1. Check 4-word expressions
  for (let i = 0; i <= n - 4; i++) {
    if (usedIndices.has(i) || usedIndices.has(i + 1) || usedIndices.has(i + 2) || usedIndices.has(i + 3)) continue;
    const phraseKey = `${cleaned[i]} ${cleaned[i + 1]} ${cleaned[i + 2]} ${cleaned[i + 3]}`;
    if (RUSSIAN_COLLOCATIONS[phraseKey]) {
      const info = RUSSIAN_COLLOCATIONS[phraseKey]!;
      const wordIndices = [i, i + 1, i + 2, i + 3];
      wordIndices.forEach((idx) => usedIndices.add(idx));
      detected.push({
        phraseText: `${words[i]} ${words[i + 1]} ${words[i + 2]} ${words[i + 3]}`,
        rawText: phraseKey,
        startIndex: i,
        endIndex: i + 3,
        wordIndices,
        translationUz: info.uz,
        translationEn: info.en,
        category: info.category,
      });
    }
  }

  // 2. Check 3-word expressions
  for (let i = 0; i <= n - 3; i++) {
    if (usedIndices.has(i) || usedIndices.has(i + 1) || usedIndices.has(i + 2)) continue;
    const phraseKey = `${cleaned[i]} ${cleaned[i + 1]} ${cleaned[i + 2]}`;
    if (RUSSIAN_COLLOCATIONS[phraseKey]) {
      const info = RUSSIAN_COLLOCATIONS[phraseKey]!;
      const wordIndices = [i, i + 1, i + 2];
      wordIndices.forEach((idx) => usedIndices.add(idx));
      detected.push({
        phraseText: `${words[i]} ${words[i + 1]} ${words[i + 2]}`,
        rawText: phraseKey,
        startIndex: i,
        endIndex: i + 2,
        wordIndices,
        translationUz: info.uz,
        translationEn: info.en,
        category: info.category,
      });
    }
  }

  // 3. Check 2-word expressions (Bigrams)
  for (let i = 0; i <= n - 2; i++) {
    if (usedIndices.has(i) || usedIndices.has(i + 1)) continue;
    const phraseKey = `${cleaned[i]} ${cleaned[i + 1]}`;
    if (RUSSIAN_COLLOCATIONS[phraseKey]) {
      const info = RUSSIAN_COLLOCATIONS[phraseKey]!;
      const wordIndices = [i, i + 1];
      wordIndices.forEach((idx) => usedIndices.add(idx));
      detected.push({
        phraseText: `${words[i]} ${words[i + 1]}`,
        rawText: phraseKey,
        startIndex: i,
        endIndex: i + 1,
        wordIndices,
        translationUz: info.uz,
        translationEn: info.en,
        category: info.category,
      });
    }
  }

  return detected;
}
